name: cli_router
description: >
  Router for CLIs inspired by shelf_router that uses spaces between segments.
  Supports cmd('route subroute', handler), mount('prefix', subRouter),
  dynamic parameters <id>, GNU-style flags, and shelf-like middlewares.
version: 0.0.1

repository: https://github.com/macss-dev/cli_router
homepage: https://macss.dev
issue_tracker: https://github.com/macss-dev/cli_router/issues
documentation: https://macss.dev/cli_router

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - cli
  - router
  - macss